# Generated by Django 2.1.1 on 2018-09-27 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('In Use', 'In Use'), ('In Stock', 'In Stock'), ('In Maintenace', 'In Maintenance'), ('Damaged', 'Damaged')], default='In Stock', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Not Assigned', max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('department', models.CharField(max_length=20)),
                ('campus', models.ForeignKey(default='Not Assigned', on_delete=django.db.models.deletion.CASCADE, to='IMS.Campus')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS.Teacher'),
        ),
    ]
