# Generated by Django 2.1.1 on 2018-09-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='IMS.Teacher'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('In Stock', 'In Stock'), ('In Maintenance', 'In Maintenance'), ('Damaged', 'Damaged')], default='In Stock', max_length=20),
        ),
    ]
