# Generated by Django 2.1.1 on 2018-10-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0002_auto_20180928_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='phone',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
