# Generated by Django 2.1.1 on 2018-10-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0004_auto_20181003_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='Not Assigned', max_length=40),
        ),
    ]
