# Generated by Django 2.1.1 on 2018-10-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0005_auto_20181003_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[(1, 'In Use'), (2, 'In Stock'), (3, 'In Maintenance'), (4, 'Damaged')], default=2, max_length=20),
        ),
    ]
