# Generated by Django 2.1.1 on 2018-10-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0006_auto_20181023_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[(1, 'In Use'), (2, 'In Stock'), (3, 'In Maintenance'), (4, 'Damaged')], max_length=20),
        ),
    ]
