# Generated by Django 2.1.1 on 2018-12-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS', '0007_auto_20181024_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('In Stock', 'In Stock'), ('In Maintenance', 'In Maintenance'), ('Damaged', 'Damaged')], max_length=20),
        ),
    ]
